openapi: 3.1.0
info:
  title: Canva Connect OAuth Relay for ChatGPT Actions
  version: 2.0.0

servers:
  - url: https://api.canva.com/rest/v1
    description: Canva Connect REST base

components:
  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://YOUR-RELAY-DOMAIN/api/oauth/authorize
          tokenUrl: https://YOUR-RELAY-DOMAIN/api/oauth/token
          scopes:
            design:content:write: Create designs
            design:content:read: Read designs and export
            folder:read: Read folders and items
            autofill:write: Create autofill jobs
            autofill:read: Read autofill job status
  schemas: {}

security:
  - oAuth2:
      - design:content:write
      - design:content:read
      - folder:read
      - autofill:write
      - autofill:read

paths: {}
